---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-controller-alluxio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-controller-alluxio
  template:
    metadata:
      labels:
        app: csi-controller-alluxio
    spec:
      hostNetwork: true
      serviceAccountName: csi-controller-alluxio-sa
      containers:
        - name: csi-provisioner
          # For kubernetes 1.13 or above
          image: quay.io/k8scsi/csi-provisioner:v1.4.0
          args:
            - "-v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=60s"
            - "--volume-name-prefix=alluxio"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: alluxio-csi
          image: alluxio/alluxio-csi:latest
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/alluxio-csi"]
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: socket-dir
          emptyDir: {}