apiVersion: v1
kind: PersistentVolume
metadata:
  name: alluxio-pv
  labels:
    name: alluxio-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: alluxio
    volumeHandle: alluxio
    volumeAttributes:
      alluxio.master.hostname: "MASTER_HOST_NAME"