---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alluxio
provisioner: alluxio
parameters:
  alluxio.master.hostname: "MASTER_HOST_NAME"
volumeBindingMode: Immediate
mountOptions:
  - allow_other